PATH={{ homebrew_path }}:$PATH
PATH=$HOME/bin:$PATH
export PATH

# Add bash completion if we have it
export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,aliases,functions,extra,kuberc}; do
  [ -r "$file" ] && source "$file"
done
unset file

alias ll="ls -alh"

